// Copyright (c) 2019 Intel Corporation. All rights reserved.
// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Portions Copyright 2017 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE-BSD-3-Clause file.
//
// SPDX-License-Identifier: Apache-2.0 AND BSD-3-Clause

use std::env;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Tell cargo to rerun build script if headers change
    println!("cargo:rerun-if-changed=third-party/linux-headers/bootparam.h");
    println!("cargo:rerun-if-changed=third-party/linux-headers/elf.h");
    println!("cargo:rerun-if-changed=third-party/linux-headers/start_info.h");

    // Generate bootparam.rs
    let bootparam_bindings = bindgen::Builder::default()
        .header("third-party/linux-headers/bootparam.h")
        .derive_default(true)
        .derive_partialeq(true)
        .generate_comments(false)
        .use_core()
        .ctypes_prefix("::std::os::raw")
        // Add copyright header
        .raw_line("// Copyright (c) 2019 Intel Corporation. All rights reserved.")
        .raw_line("// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.")
        .raw_line("//")
        .raw_line("// Portions Copyright 2017 The Chromium OS Authors. All rights reserved.")
        .raw_line("// Use of this source code is governed by a BSD-style license that can be")
        .raw_line("// found in the LICENSE-BSD-3-Clause file.")
        .raw_line("//")
        .raw_line("// SPDX-License-Identifier: Apache-2.0 AND BSD-3-Clause")
        .raw_line("")
        .raw_line("/*")
        .raw_line(" * automatically generated by rust-bindgen")
        .raw_line(" * From upstream linux arch/x86/include/uapi/asm/bootparam.h at commit:")
        .raw_line(" * 48b1320a674e1ff5de2fad8606bee38f724594dc")
        .raw_line(" */")
        .raw_line("")
        .generate()
        .expect("Unable to generate bootparam bindings");

    bootparam_bindings
        .write_to_file(out_dir.join("bootparam.rs"))
        .expect("Couldn't write bootparam.rs");

    // Generate elf.rs
    let elf_bindings = bindgen::Builder::default()
        .header("third-party/linux-headers/elf.h")
        .derive_default(true)
        .derive_partialeq(true)
        .generate_comments(false)
        .use_core()
        .ctypes_prefix("::std::os::raw")
        // Add copyright header
        .raw_line("// Copyright © 2020, Oracle and/or its affiliates.")
        .raw_line("//")
        .raw_line("// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.")
        .raw_line("//")
        .raw_line("// Portions Copyright 2017 The Chromium OS Authors. All rights reserved.")
        .raw_line("// Use of this source code is governed by a BSD-style license that can be")
        .raw_line("// found in the LICENSE-BSD-3-Clause file.")
        .raw_line("//")
        .raw_line("// SPDX-License-Identifier: Apache-2.0 AND BSD-3-Clause")
        .raw_line("")
        .raw_line("/*")
        .raw_line(" * automatically generated by rust-bindgen")
        .raw_line(" * From upstream linux include/uapi/linux/elf.h at commit:")
        .raw_line(" * 48b1320a674e1ff5de2fad8606bee38f724594dc")
        .raw_line(" */")
        .raw_line("")
        .generate()
        .expect("Unable to generate elf bindings");

    elf_bindings
        .write_to_file(out_dir.join("elf.rs"))
        .expect("Couldn't write elf.rs");

    // Generate start_info.rs
    let start_info_bindings = bindgen::Builder::default()
        .header("third-party/linux-headers/start_info.h")
        .derive_default(true)
        .derive_partialeq(true)
        .generate_comments(false)
        .use_core()
        .ctypes_prefix("::std::os::raw")
        // Add copyright header
        .raw_line("// Copyright © 2020, Oracle and/or its affiliates.")
        .raw_line("//")
        .raw_line("// Copyright (c) 2019 Intel Corporation. All rights reserved.")
        .raw_line("// Copyright (c) 2016, Citrix Systems, Inc.")
        .raw_line("//")
        .raw_line("// SPDX-License-Identifier: Apache-2.0 AND BSD-3-Clause AND MIT")
        .raw_line("")
        .raw_line("/*")
        .raw_line(" * automatically generated by rust-bindgen")
        .raw_line(" * From upstream linux include/xen/interface/hvm/start_info.h at commit:")
        .raw_line(" * 48b1320a674e1ff5de2fad8606bee38f724594dc")
        .raw_line(" */")
        .raw_line("")
        .generate()
        .expect("Unable to generate start_info bindings");

    start_info_bindings
        .write_to_file(out_dir.join("start_info.rs"))
        .expect("Couldn't write start_info.rs");
}
